- name: Configure the new VM
  hosts: 10.13.104.41
  gather_facts: yes
  become: yes
  vars:
    ansible_host: 10.13.104.41
    ansible_user: sysadmin
    ansible_ssh_pass: "123456"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: espresso-instance
